---
- name: Download and extract Apache Kafka
  hosts: localhost
  connection: local
  tasks:
    - name: Create directory for Kafka
      become: yes
      file:
        path: /opt/kafka
        state: directory
        mode: '0755'

    - name: Download Kafka
      get_url:
        url: "https://downloads.apache.org/kafka/4.1.0/kafka_2.13-4.1.0.tgz"
        dest: /tmp/kafka.tgz
        mode: '0644'

    - name: Extract Kafka
      become: yes
      unarchive:
        src: /tmp/kafka.tgz
        dest: /opt/kafka
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /opt/kafka/bin
