---
- name: Скачать и распаковать архив Apache Kafka
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Скачать архив Kafka
      get_url:
        url: "https://downloads.apache.org/kafka/3.4.0/kafka_2.13-3.4.0.tgz"
        dest: "/tmp/kafka.tgz"
        mode: '0644'

    - name: Создать папку для распаковки
      file:
        path: "/opt/kafka"
        state: directory
        mode: '0755'

    - name: Распаковать архив в /opt/kafka
      unarchive:
        src: "/tmp/kafka.tgz"
        dest: "/opt/kafka"
        remote_src: yes
        extra_opts: [--strip-components=1]
